---
- name: Get Vector
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/0.22.2/vector_0.22.2-1_amd64.deb"
    dest: "~/vector_0.22.2-1_amd64.deb"
- name: Install Vector
  become: true
  apt:
    deb: /home/vagrant/vector_0.22.2-1_amd64.deb
