---
- name: Install Vector
  ansible.builtin.include_tasks:
    file: install_{{ ansible_facts.pkg_mgr }}.yml

- name: Configure Vector
  ansible.builtin.include_tasks:
    file: configure_vector.yml

    #- name: Configure service
    #ansible.builtin.include_tasks:
    #file: configure_service.yml
